"""English given names inside Chinese text ("Jason說好", "這是Annie的電腦").

The privacy filter often misses a lone English name among Chinese characters. Inside
Chinese text, a capitalized English word that is a common given name is almost always
a person, so a list is enough. English-only lines are left to the model: there "Grace
period" or "Mark the date" are ordinary words.
"""

from __future__ import annotations

import re
from functools import cache
from importlib.resources import files

from ..lang import has_cjk
from ..mapping import PERSON
from .base import Span

_WORD = r"[A-Z][a-z]+(?:[-'’][A-Z]?[a-z]+)*"
# Capitalized words in a row ("Hi Emily Chen"), not touching other letters or digits.
WORDS_RE = re.compile(rf"(?<![A-Za-z0-9_]){_WORD}(?: {_WORD})*(?![A-Za-z0-9_])")
# A given name takes at most this many capitalized words after it as its surname(s).
MAX_SURNAMES = 2


@cache
def given_names() -> frozenset[str]:
    """Generated by tools/update_names.py."""
    return frozenset(files("datafuzzy").joinpath("given_names.txt").read_text().split())


class GivenNameDetector:
    name = "given-names"

    def detect(self, text: str) -> list[Span]:
        names = given_names()
        spans: list[Span] = []
        for line in re.finditer(r"[^\n]+", text):
            if not has_cjk(line.group()):
                continue
            for m in WORDS_RE.finditer(line.group()):
                words = m.group().split(" ")
                first = next((i for i, w in enumerate(words) if w in names), None)
                if first is None:
                    continue
                # "Hi Sarah" -> "Sarah"; "Emily Chen" -> "Emily Chen".
                value = " ".join(words[first:first + 1 + MAX_SURNAMES])
                start = line.start() + m.start() + len(" ".join(words[:first])) + (first > 0)
                spans.append(Span(start, start + len(value), PERSON, value))
        return spans
